config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#show"
  get '/dashboard', to: 'welcome#index'
  get "/auth/twitter", as: :login
  get "/auth/twitter/callback", to: "sessions#create"
  get "/logout", to: "sessions#destroy", as: :logout
  resources :favorites, only: [:create]
  resources :tweets, only: [:create]
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.extra.raw_info.name
      new_user.screen_name        = auth_info.extra.raw_info.screen_name
      new_user.oauth_token        = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def service_connection
    @service_connection ||= TwitterService.new(current_user)
  end

  def sheep_text(tweet)
    baa_text = tweet.text.split(/\W+/).map!.with_index do |word, index|
      if index % 4 == 0
        word = "baa"
      elsif index % 4 == 2
        word = "sheep"
      elsif word[0..3] == "http"
        word = ""
      else
        word
      end
    end
    baa_text.join(" ")
  end

  helper_method :current_user, :service_connection, :sheep_text
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    service_connection.favorite(params[:tweet_id])
    redirect_to dashboard_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to dashboard_path
  end

  def destroy
    session.clear
    flash[:logout] = "Goodbye!"
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def create
    service_connection.post(params[:tweet][:text])
    redirect_to dashboard_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    if current_user.nil?
      redirect_to root_path
    end
    @service = service_connection.client
    @timeline = service_connection.timeline
    @name = service_connection.client.user.name
  end

  def show
    if current_user
      redirect_to dashboard_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Critter</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="top-bar">
  <div class="top-bar-left">
  <ul class="menu">
  <li class="menu-text">Critter - Twitter for Sheep</li>
  </ul>
  </div>
  <div class="top-bar-right">
  <ul class="menu">
  <% if current_user %>
  <li><a href="<%= logout_path %>">Logout</a></li>
  <% else %>
  <li><a href="<%= login_path %>">Login</a></li>
  <% end %>
  </ul>
  </div>
  </div>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<!doctype html>
<html class="no-js" lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Critter</title>
<link rel="stylesheet" href="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.min.css">
</head>
<body>

<div class="callout large primary">
<div class="row column text-center">
<h1><%= @name %>'s Critter Feed</h1>
</div>
</div>
<div class="row" id="content">
<div class="medium-8 columns">

<% @timeline.each_with_index do |tweet, index| %>
<div class="tweet-<%= index %>">
<img class="thumbnail" src="<%= tweet.user.profile_image_url %>">
<%= sheep_text(tweet) %><br><br>
<div class="callout">
<ul class="menu simple">
<li>Author: <%= tweet.user.name %></li>
<li><a href="<%= tweet.user.url %>">@<%= tweet.user.screen_name %></a></li>
<li><a><%= tweet.retweet_count %> Retweets</a></li>
<li><a><%= tweet.favorite_count %> Favorites</a></li>
<li>
  <% if tweet.favorited? %>
    <li>Favorited!</li>
  <% else %>
    <%= link_to "Favorite", favorites_path(tweet_id: tweet.id), method: :post %>
  <% end %>
</li>
</ul>
</div>
</div>
<% end %>

</div>
<div class="medium-3 columns" data-sticky-container>
<div class="sticky" data-sticky data-anchor="content">
<h4><a href="<%= @service.user.url %>">@<%= @service.user.screen_name %></a></h4>
<ul>
<img class="thumbnail" src="<%= @service.user.profile_image_url %>">
<li>Follower Count: <%= @service.user.followers_count %></li>
<li>Friends Count: <%= @service.user.friends_count %></li>
<%= form_tag(tweets_path, method: :post) do %>
  <%= label_tag "Compose a Tweet" %>
  <%= text_field_tag "tweet[text]" %>
  <%= submit_tag "Tweet" %>
<% end %>
</ul>
</div>
</div>
</div>
<div class="row column">
<ul class="pagination" role="navigation" aria-label="Pagination">
<li class="disabled">Previous</li>
<li class="current"><span class="show-for-sr">You're on page</span> 1</li>
<li><a href="#" aria-label="Page 2">2</a></li>
<li><a href="#" aria-label="Page 3">3</a></li>
<li><a href="#" aria-label="Page 4">4</a></li>
<li class="ellipsis"></li>
<li><a href="#" aria-label="Page 12">12</a></li>
<li><a href="#" aria-label="Page 13">13</a></li>
<li><a href="#" aria-label="Next page">Next</a></li>
</ul>
</div>
<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
<script>
      $(document).foundation();
    </script>
</body>
</html>